/**
 * Author: Ruan Petrus
 * Description: Given a convex polygon you have to make k cuts, and have no maximize the
 * area of the smallest polygon generated by the cuts
 * Time: O(n^3)
 * Status: stress-tested
 */

#include <bits/stdc++.h>

using namespace std;

#define endl '\n'
#define pb push_back
#define eb emplace_back
#define all(x) begin(x), end(x)
#define debug(x) cout << #x << ": " << (x) << endl
#define rep(i, a, b) for (int i = a; i < (int)(b); i++)
#define irep(i, a, b) for (int i = a; i >= (int)(b); i--)

#define inbounds(x, l, r) ((l) <= (x) && (x) <= (r))
#define L0(res...) [&](){ return res; }
#define L1(res...) [&](auto const & x){ return res; }
#define L2(res...) [&](auto const & x, auto const& y){ return res; }
#define sz(x) (int)x.size()

template<class T> inline void chmin(T & a, const T b){ if (a > b) a = b; }
template<class T> inline void chmax(T & a, const T b){ if (a < b) a = b; }

typedef pair<int, int> pii;
typedef vector<int> vi;
typedef long long ll;
typedef long double ld;

const ll oo = 0x3f3f3f3f3f3f3f3f;

template <class T> int sgn(T x) { return (x > 0) - (x < 0); }
template<class T>
struct Point {
	typedef Point P;
	T x, y;
	explicit Point(T x=0, T y=0) : x(x), y(y) {}
	bool operator<(P p) const { return tie(x,y) < tie(p.x,p.y); }
	bool operator==(P p) const { return tie(x,y)==tie(p.x,p.y); }
	P operator+(P p) const { return P(x+p.x, y+p.y); }
	P operator-(P p) const { return P(x-p.x, y-p.y); }
	P operator*(T d) const { return P(x*d, y*d); }
	P operator/(T d) const { return P(x/d, y/d); }
	T dot(P p) const { return x*p.x + y*p.y; }
	T cross(P p) const { return x*p.y - y*p.x; }
	T cross(P a, P b) const { return (a-*this).cross(b-*this); }
	T dist2() const { return x*x + y*y; }
	double dist() const { return sqrt((double)dist2()); }
	// angle to x-axis in interval [-pi, pi]
	double angle() const { return atan2(y, x); }
	P unit() const { return *this/dist(); } // makes dist()=1
	P perp() const { return P(-y, x); } // rotates +90 degrees
	P normal() const { return perp().unit(); }
	// returns point rotated 'a' radians ccw around the origin
	P rotate(double a) const {
		return P(x*cos(a)-y*sin(a),x*sin(a)+y*cos(a)); }
	friend ostream& operator<<(ostream& os, P p) {
		return os << "(" << p.x << "," << p.y << ")"; }
};

template<class P> bool onSegment(P s, P e, P p) {
	return p.cross(s, e) == 0 && (s - p).dot(e - p) <= 0;
}

template<class P>
int sideOf(P s, P e, P p) { return sgn(s.cross(e, p)); }

template<class P>
int sideOf(const P& s, const P& e, const P& p, double eps) {
	auto a = (e-s).cross(p-s);
	double l = (e-s).dist()*eps;
	return (a > l) - (a < -l);
}

typedef Point<ll> P;

const int mxN = 2e2 + 5;

P A[mxN];
ll psum[mxN];

pair<int, ll> dp[mxN][mxN];

void solve() {
	int n, k;
	cin >> n >> k;
	rep(i, 0, n) cin >> A[i].x >> A[i].y;

	A[n] = A[0];
	rep(i, 1, n) psum[i] = psum[i-1] + A[i-1].cross(A[i]);
	psum[n] = psum[n-1] + A[n-1].cross(A[0]);

	auto area = [&](int i, int j) -> ll {
		if (i == 0 && j == n) return abs(psum[n]);
		else                  return abs(psum[j] - psum[i] + A[j].cross(A[i]));
	};

	auto works = [&](ll mid) {
		for (int i = n; i >= 0; i--) for (int j = i+1; j <= n; j++) {
			ll total = area(i, j);
			if (total < mid) {
				dp[i][j] = {0, total};
				continue;
			}
			dp[i][j] = {0, total};
			rep(k, i+1, j) {
				auto res1 = dp[i][k];
				auto res2 = dp[k][j];

				ll left = total - area(i, k) - area(k, j);

				chmax(dp[i][j], {res1.first + res2.first, left + res1.second + res2.second});

				if (res2.second >= mid && res1.second >= mid) {
					chmax(dp[i][j], {2 + res1.first + res2.first, left});
				}
				if (res1.second >= mid) {
					chmax(dp[i][j], {1 + res1.first + res2.first, left + res2.second});
				}
				if (res2.second >= mid) {
					chmax(dp[i][j], {1 + res1.first + res2.first, left + res1.second});
				}
			}
		}

		return dp[0][n].first - (dp[0][n].second < mid) >= k;
	};

	ll ans = 0;
	ll l = 1;
	ll r = 1e18;
	while(l <= r) {
		ll mid = l +(r-l)/2;
		if (works(mid)) {
			ans = mid;
			l = mid + 1;
		}
		else r = mid - 1;
	}
	cout << ans << endl;
}

int32_t main() {
	ios_base::sync_with_stdio(0); cin.tie(0); cout.tie(0);
	int t = 1;
	// cin >> t;
	for (int i = 0; i < t; i++) {
		solve();
	}
	return 0;
}
